os: Windows Server 2012

environment:
  matrix:
    - python_version: "C:\\Python36"
    - python_version: "C:\\Python36-x64"
    - python_version: "C:\\Python37"
    - python_version: "C:\\Python37-x64"
    - python_version: "C:\\Python38"
    - python_version: "C:\\Python38-x64"

install:
  - "SET PATH=%python_version%;%python_version%\\Scripts;%PATH%"
  - "pip install setuptools"
  - "pip install --upgrade setuptools"
  - "pip install -e ."
  - "pip list"

test_script:
  - "python setup.py test"

build: off